import type { SpriteGrid } from './sprites';

/**
 * P11 boss sprites (docs/art-direction.md §Bosses): 20×20, baked at ×4 via
 * BOSS_SPRITE_SCALE — the largest and most elaborate actors in the game.
 * Keys are the boss enemy ids. Palette resolves through paletteFor(element).
 */
export const BOSS_SPRITE_SCALE = 4;

export const BOSS_GRIDS: Record<string, SpriteGrid> = {
  // Ember: a magma titan under a roaring flame crown; stone furnace heart.
  cinderlord: [
    '..g....gggggg....g..',
    '.gg...gllllllg...gg.',
    '..ggggllllmmllgggg..',
    '...glllgllmmglllg...',
    '...ollmmgggggmmdo...',
    '..ollmmmmmmmmmmddo..',
    '..olmgmmmmmmmmgmdo..',
    '.ollmmgmmmmmmgmmddo.',
    '.olmmmmosssommmmddo.',
    '.olmmmoSwSwSommmddo.',
    '.olmmmoSgSgSommmddo.',
    '.olmmmosssssommmddo.',
    '..olmmmosssommmddo..',
    '..ollmmmmmmmmmdddo..',
    '...ollmmmmmmmdddo...',
    '....ollmmmmmdddo....',
    '...og.ollmdddo.go...',
    '..og...olmddo...go..',
    '.g......oddo......g.',
    '.........oo.........',
  ],
  // Frost: a glacier wraith — sheared crystal crest, frozen core eye.
  rimelord: [
    '....og........go....',
    '...olg..gggg..glo...',
    '...olg.ogllmo.glo...',
    '....o.ogllmmdo.o....',
    '.....ogglllmmdo.....',
    '....oglllllmmddo....',
    '...ogllllmmmmdddo...',
    '...olllgmmmmgdddo...',
    '..oglllmosomddddgo..',
    '..olllmoSwSomdddgo..',
    '..olllmosssomddddo..',
    '..ogllmmmmmmmdddgo..',
    '...ollllmmmmdddoo...',
    '...oglllmmmddddgo...',
    '....ogllmmdddogo....',
    '.....ollmmdddo......',
    '....og.olmdo.go.....',
    '...og...oo....go....',
    '..g.............g...',
    '....................',
  ],
  // Nature: a moss colossus around a glowing heartwood cage.
  verdantheart: [
    '..gg....g..g....gg..',
    '.oglg..glggmg..glgo.',
    '.oglmggllmmmdggmlgo.',
    '..ogllmmmmmmmmlldo..',
    '...ollgmmmmmmglddo..',
    '..ollmmmwwwwmmmddo..',
    '.ollmmmwSSSSwmmdddo.',
    '.olmmmwSSggSSwmdddo.',
    '.olmmwSSggggSSwdddo.',
    '.olmmwSSggggSSwdddo.',
    '.olmmmwSSggSSwmdddo.',
    '.ollmmmwSSSSwmmdddo.',
    '..ollmmmwwwwmmdddo..',
    '..oollmmmmmmmmddoo..',
    '.og.ollmmmmmddo..go.',
    '.g...ollmmmddo....g.',
    '......ollmddo.......',
    '.......olddo........',
    '........oo..........',
    '....................',
  ],
  // Storm: a horned storm herald crackling with orbit sparks.
  tempestcaller: [
    '......g......g......',
    '.....glg....glg.....',
    '....gllg....gllg....',
    '....ollmggggmllo....',
    '...ollmmllllmmddo...',
    '..ollmmmlgglmmmddo..',
    '..olmgmmgggmmmgmdo..',
    '.ollmmmggggggmmmdo..',
    '.olmmmgg.gg.ggmmdo..',
    '.olmmg...gg...gmdo..',
    '..olmmgggggggmmdo...',
    '..ollmmmmmmmmmdo....',
    '...ollmmmmmmddo.....',
    '..g.ollmmmdddo.g....',
    '.glg.olmmdddo.glg...',
    '..g...olmddo...g....',
    '.......oddo.........',
    '....g...oo...g......',
    '...glg......glg.....',
    '....g........g......',
  ],
  // Radiant: a sun seraph — full halo wheel, layered light. Glow un-outlined.
  luminarch: [
    '.........gg.........',
    '......ggggggg.......',
    '....gg.glllg.gg.....',
    '...g..gllllmg..g....',
    '..g..gllllmmdg..g...',
    '.g..glllllmmmdg..g..',
    '.g..gllwwwwmmdg..g..',
    '..g.glwwSSwwmdg.g...',
    '....glwSggSwmdg.....',
    '....glwSggSwmdg.....',
    '....glwwSSwwmdg.....',
    '..g.gllwwwwmmdg.g...',
    '.g..glllllmmmdg..g..',
    '.g...gllllmmdg...g..',
    '..g...glllmdg...g...',
    '...g...glmdg...g....',
    '....gg..gg..gg......',
    '......ggggggg.......',
    '.........gg.........',
    '....................',
  ],
  // Shadow: a horned void shade with a hollow rune mouth.
  umbrageist: [
    '....oo........oo....',
    '...oddo......oddo...',
    '..oddmdoooooodmddo..',
    '..odmmdddddddmmddo..',
    '.odmmmmmmmmmmmmmddo.',
    '.odmgmmmmmmmmmgmddo.',
    '.odmmmgmmmmmmgmmddo.',
    '.odmmggmmmmmmggmddo.',
    '..odmmmogggommmddo..',
    '..odmmog...gommdo...',
    '..odmmog...gommdo...',
    '...odmmogggommddo...',
    '...oddmmmmmmmdddo...',
    '....oddmmmmmdddo....',
    '.....oddmmdddoo.....',
    '......oddmdddo......',
    '....o..odddo..o.....',
    '...o....odo....o....',
    '..o......o......o...',
    '....................',
  ],
};
