import type { SpriteGrid } from './sprites';

/**
 * 12×12 enemy sprites (36px baked) — archetype-first silhouettes per
 * docs/art-direction.md: armored = wide + stone plates, swarm = tiny,
 * fast = sleek dart, stealth = hooded wisp (alpha applied at render time).
 */
const E = '............';

export const ENEMY_GRIDS: Record<string, SpriteGrid> = {
  // Baseline shadow blob with glowing eyes and a wispy tail.
  gloomling: [
    E,
    '....oooo....',
    '...ollmmo...',
    '..ogllmmdo..',
    '..olgmmgdo..',
    '..ollmmmdo..',
    '..ollmmmdo..',
    '..ollmmddo..',
    '...olmmdo...',
    '....omdo....',
    '.....oo.....',
    E,
  ],
  // Armored: broad dome of stone plates over a mossy underbelly, stubby feet.
  stoneshell: [
    E,
    '...oooooo...',
    '..owSSSSso..',
    '.owSwSwSsso.',
    '.owSSmSSsso.',
    '.oSSsSsSsso.',
    '.owSSmSSsso.',
    '.oSsSsSssso.',
    '..osssssso..',
    '..oddddddo..',
    '...oo..oo...',
    E,
  ],
  // Fast: a streaking flame dart with a trailing ember.
  cinderwisp: [
    '.....gg.....',
    '....gllg....',
    '....glmg....',
    '...gllmmg...',
    '...glmmdg...',
    '...olmmdo...',
    '...olmddo...',
    '....omdo....',
    '....omdo....',
    '.....oo.....',
    '.....g......',
    E,
  ],
  // Swarm: a tiny ice mite — deliberately small in the frame.
  frostmite: [
    E, E, E,
    '....oooo....',
    '...ogllmo...',
    '...ollmmo...',
    '...olmmdo...',
    '...o.oo.o...',
    E, E, E, E,
  ],
  // Stealth: a hooded shade with glowing eyes, trailing off into wisps.
  duskstalker: [
    '....oooo....',
    '...odddmo...',
    '..oddmmmdo..',
    '..odgmmgdo..',
    '..oddmmmdo..',
    '..odddmddo..',
    '...oddmdo...',
    '....oddo....',
    '.....oo.....',
    '....o..o....',
    E, E,
  ],
  // P11: the Cinderlord's split spawn — a small licking flame, rounder and
  // brighter than cinderwisp's dart so the two read apart mid-swarm.
  flamewisp: [
    E, E,
    '....oggo....',
    '...ogllgo...',
    '..oglmmlgo..',
    '..oglmmlgo..',
    '..oglmmlgo..',
    '...omddmo...',
    '....oddo....',
    '.....oo.....',
    E, E,
  ],
  // ---- P12 Frostfell family. Frost ramp; archetype-first silhouettes.
  // Swarm: a six-point snow fleck — even smaller-read than frostmite.
  driftmote: [
    E, E, E,
    '.....gg.....',
    '...glllmg...',
    '....glmg....',
    '...gllmmg...',
    '.....oo.....',
    E, E, E, E,
  ],
  // Fast: a lunging shard-wolf — low, long, fangs forward.
  icefang: [
    E, E, E,
    '..og.....g..',
    '.ollgg.gg...',
    '.olllmmmmg..',
    '..ollmmmddo.',
    '...olmmddo..',
    '....oo.oo...',
    E, E, E,
  ],
  // Armored: a faceted glacier dome over stubby feet.
  glacierback: [
    E,
    '...oooooo...',
    '..owwllSso..',
    '.owwlwlSsso.',
    '.owlwmwlsso.',
    '.oSwlwlwsso.',
    '.owlwmwlsso.',
    '.oSswlwssso.',
    '..osssssso..',
    '..oddddddo..',
    '...oo..oo...',
    E,
  ],
  // Stealth: a blizzard phantom — crystal-crowned hood, trailing to nothing.
  rimewraith: [
    '....og.go...',
    '...ogddgo...',
    '..oddmmmdo..',
    '..odgmmgdo..',
    '..oddmmmdo..',
    '..odmmmddo..',
    '...odmmdo...',
    '....odmo....',
    '.....odo....',
    '....o..o....',
    E, E,
  ],
  // Bruiser: a headless slab of packed ice — pure mass, no plates.
  frostbrand: [
    E,
    '....oooo....',
    '..oommmmoo..',
    '.olmmllmmdo.',
    '.olmlmmlmdo.',
    '.olmmmmmmdo.',
    '.ollmmmmddo.',
    '.olmmmmmddo.',
    '..olmmmddo..',
    '..oo.oo.oo..',
    E, E,
  ],

  // ---- P12 Verdant Deep family. Nature ramp.
  // Swarm: a toddling spore-cap.
  sporeling: [
    E, E,
    '....oooo....',
    '...olllmo...',
    '..ollgmmdo..',
    '..oommoo....',
    '....omo.....',
    '....o.o.....',
    E, E, E, E,
  ],
  // Fast: a bounding briar-hound — thorned spine, nose down.
  thornhound: [
    E, E,
    '...g..g.....',
    '..ogllgg....',
    '.olllmmmg...',
    '.ollmmmmdo..',
    '..olmmmddo..',
    '...omdodo...',
    '...oo..oo...',
    E, E, E,
  ],
  // Armored: living bark plates over a heartwood core.
  barkhide: [
    E,
    '...oooooo...',
    '..osSsSsso..',
    '.oSsmSmSsso.',
    '.osSgSgSsso.',
    '.oSsmSmSsso.',
    '.osSsSsSsso.',
    '.oSssSsssso.',
    '..osssssso..',
    '..oddddddo..',
    '...oo..oo...',
    E,
  ],
  // Stealth: a dappled glade shade — leaf-hooded, eyes of spore-light.
  gladeshade: [
    '....oooo....',
    '...odmddo...',
    '..odmmmddo..',
    '..odgmmgdo..',
    '..oddmmddo..',
    '..odmdmddo..',
    '...odmmdo...',
    '....oddo....',
    '.....odo....',
    '...o..o.....',
    E, E,
  ],
  // Bruiser: a moss-backed swamp colossus filling the frame.
  mirehulk: [
    '....oooo....',
    '..oommmmoo..',
    '.olmmggmmdo.',
    '.olmmmmmmdo.',
    'olmmlmmlmmdo',
    'olmmmmmmmddo',
    'olmlmmmlmddo',
    'olmmmmmmmddo',
    '.olmmmmmddo.',
    '..ommoommo..',
    '..oo....oo..',
    E,
  ],
  // ---- P13 Storm Reach family. Storm ramp; speed-first silhouettes.
  // Swarm: a crackling static fleck — jagged, tiny in the frame.
  sparkmote: [
    E, E, E,
    '.....gg.....',
    '....glmg....',
    '...gllmmg...',
    '....glmg....',
    '...g.oo.g...',
    E, E, E, E,
  ],
  // Fast: a wind-runner at full stretch — legs thrown long, head down.
  galestrider: [
    E, E, E,
    '.g.......g..',
    '..gllggll...',
    '.olllmmmmg..',
    '..ollmmmddo.',
    '.o..lmmd..o.',
    '....oo.oo...',
    E, E, E,
  ],
  // Armored: a storm-bison under fulgurite plates — widest dome yet.
  thunderhide: [
    E,
    '...oooooo...',
    '..oswSwSso..',
    '.oswSgSwsso.',
    '.oswSmSwsso.',
    '.oSswSwSsso.',
    '.oswSmSwsso.',
    '.oSswSwssso.',
    '..osssssso..',
    '..oddddddo..',
    '...oo..oo...',
    E,
  ],
  // Stealth: a squall phantom striding inside its own mist-column.
  mistwalker: [
    '....og.go...',
    '...ogmmgo...',
    '..odmmmmdo..',
    '..odgmmgdo..',
    '..odmmmmdo..',
    '..oddmmddo..',
    '...odmmdo...',
    '....odmo....',
    '....o.do....',
    '...o...o....',
    E, E,
  ],
  // Bruiser: a walking thunderhead — an anvil-topped mass of packed galewind.
  stormbrute: [
    E,
    '..oooooooo..',
    '.olmmmmmmdo.',
    '.ollmggmmdo.',
    '..olmmmmdo..',
    '.olmmlmmmdo.',
    '.olmmmmmddo.',
    '.ollmmmmddo.',
    '..olmmmddo..',
    '..oo.oo.oo..',
    E, E,
  ],
  // ---- P13 Radiant Summits family. Radiant ramp; light-and-shield silhouettes.
  // Swarm: a drifting fleck of hard light — a six-ray glint.
  lumenmote: [
    E, E,
    '.....g......',
    '....glg.....',
    '...gllmg....',
    '....glmg....',
    '.....oo.....',
    E, E, E, E, E,
  ],
  // Fast: a streak of sunrise — a comet-head with a trailing flare.
  raywisp: [
    '.....gg.....',
    '....gllg....',
    '....gllmg...',
    '...gllmmg...',
    '...glmmdg...',
    '...olmmdo...',
    '....omddo...',
    '....omdo....',
    '.....odo....',
    '.....oo.....',
    '.....g......',
    E,
  ],
  // Armored: a mirror-shield phalanx of one — a wall of polished plates.
  aegisbearer: [
    E,
    '...oooooo...',
    '..owwwwwso..',
    '.owwgwgwsso.',
    '.owwwmwwsso.',
    '.oSwwwwwsso.',
    '.owwwmwwsso.',
    '.oSswwwssso.',
    '..osssssso..',
    '..oddddddo..',
    '...oo..oo...',
    E,
  ],
  // Stealth: a seraph wrapped in blinding veils — wings folded to a spire.
  veilseraph: [
    '....og.go...',
    '...ogllgo...',
    '..olgmmglo..',
    '..olgmmglo..',
    '..ollmmllo..',
    '..odlmmldo..',
    '...odmmdo...',
    '....odmo....',
    '.....odo....',
    '....o..o....',
    E, E,
  ],
  // Bruiser: a grazing colossus of molten daylight filling the frame.
  sungrazer: [
    '....oooo....',
    '..oommmmoo..',
    '.olmmggmmdo.',
    '.ollmmmmmdo.',
    'olmlmmmlmmdo',
    'olmmmmmmmddo',
    'ollmmlmmmddo',
    'olmmmmmmmddo',
    '.olmmmmmddo.',
    '..ommoommo..',
    '..oo....oo..',
    E,
  ],

  // ---- P14 Umbral Depths family. Shadow ramp; darkness-first silhouettes.
  // Swarm: a fleck of living dark — a dim violet pulse.
  voidmote: [
    E, E, E,
    '.....gg.....',
    '....gmmg....',
    '...glmmdg...',
    '....gmdg....',
    '.....gg.....',
    E, E, E, E,
  ],
  // Fast: a night-flier at full glide, wings thrown wide.
  gloomwing: [
    E, E,
    '..g......g..',
    '.ogg....ggo.',
    '..oggmmggo..',
    '...ogmmgo...',
    '....olmdo...',
    '....omdo....',
    '.....oo.....',
    E, E, E,
  ],
  // Armored: a hollow carapace packed with dark — plates over a void.
  umbrahusk: [
    E,
    '...oooooo...',
    '..ossSsSso..',
    '.osSgSgSsso.',
    '.osSsmsSsso.',
    '.oSsSsSssso.',
    '.osSsmsSsso.',
    '.osssSsssso.',
    '..osssssso..',
    '..oddddddo..',
    '...oo..oo...',
    E,
  ],
  // Stealth: a hooded null in a tapering shroud.
  nullwraith: [
    '....ogo.....',
    '...ogmgo....',
    '..ogmmmgo...',
    '..odmmmdo...',
    '..odmgmdo...',
    '...odmdo....',
    '...odmdo....',
    '....odo.....',
    '....o.o.....',
    E, E, E,
  ],
  // Bruiser: a walking abyss — the toothed maw fills the frame.
  dreadmaw: [
    E,
    '..oooooooo..',
    '.olmmmmmmdo.',
    '.olgmmmmgdo.',
    '.olmmmmmmdo.',
    '.omdldldldo.',
    '.olmmmmmmdo.',
    '.ollmmmmddo.',
    '..olmmmddo..',
    '..oo.oo.oo..',
    E, E,
  ],
};
